#!/usr/bin/env bash
set -ex

OUT=target/

MODEL=rc11

if [ ! -z "$1" ]; then
   MODEL=$1
fi

CONF=model/${MODEL}.cfg

for f in `find ./tests -name "*.litmus" -type f`; do
    herd7  -o $OUT -conf $CONF $f &> $f.expected
done
